import '../globals.css';
import ThemeProvider from '@/common/theme';
import { Providers } from '@/store/provider';
import Header from '@/components/organisms/header';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import Box from '@/components/atoms/box';
import Audio from '@/components/atoms/audio';
import AuthProvider from '@/utility/AuthProvider';
import ModalContext from '@/utility/ModalContext';
import ClientLayout from './ClientLayout';

// export const metadata: Metadata = {
//   title: 'Rent Babe',
//   description: 'Generated by create next app',
// };

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ClientLayout>{children}</ClientLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

// String.prototype.toCloudFlareURL = function () {
//   let url = this;
//   if (!url) return '';

//   let get = url.split('/');

//   if (get.length > 2) {
//     if (get[2] === 'images.rentbabe.com') return `${url}`;
//   }

//   let last = get[get.length - 1];
//   let baseURI = process.env.NEXT_PUBLIC_IMAGE_PREFIX;
//   let path = '';
//   const folders = last.split('%2F');
//   for (let index = 0; index < folders.length; index++) {
//     const folder = folders[index];
//     path += `${folder}${index === folders.length - 1 ? '' : '/'}`;
//   }
//   function getURLQueryStringValue(url: string, key: string) {
//     //eslint-disable-next-line no-useless-escape
//     return decodeURIComponent(
//       url.replace(
//         new RegExp('^(?:.*[&\\?]' + encodeURIComponent(key).replace(/[\.\+\*]/g, '\\$&') + '(?:\\=([^&]*))?)?.*$', 'i'),
//         '$1'
//       )
//     );
//   }

//   const rentbh = getURLQueryStringValue(path, 'rentbh');
//   const rentbw = getURLQueryStringValue(path, 'rentbw');
//   const time = getURLQueryStringValue(path, 't');

//   const myPath = path.split('?')[0];
//   const queryWidth = rentbw ? `&rentbw=${rentbw}` : '';
//   const queryHeight = rentbh ? `&rentbh=${rentbh}` : '';
//   const queryTime = time ? `&t=${time}` : '';

//   const finalURL = `${baseURI}${myPath}?${queryHeight}${queryWidth}${queryTime}`; //baseURI + path.split("?")[0] + `?rentbh=${rentbh}&rentbw=${rentbw}` + `${time ? `&t=${time}` : ''}`
//   return finalURL;
// };
